---

version: 2

updates:

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    reviewers:
      - jkatzwinkel

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    reviewers:
      - jkatzwinkel

...
