---

name: e2e

on: [push]


jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.4.0

      - uses: actions/setup-python@v4.5.0
        with:
          python-version: '3.11'

      - uses: actions/setup-node@v3.6.0
        with:
          node-version: 18

      - name: install cypress
        run: npm ci

      - name: start webserver
        run: python -mhttp.server&

      - name: run tests against chrome
        run: >
          docker run -v `pwd`:/e2e -w /e2e --network=host cypress/included:12.15.0
          cypress run --browser chrome

      - name: run tests against firefox
        run: >
          docker run -v `pwd`:/e2e -w /e2e --network=host cypress/included:12.15.0
          cypress run --browser firefox

      - name: run tests against electron
        run: npx cypress run

...
