---

name: e2e

'on': [push]


jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5.4.0
        with:
          python-version: '3.11'

      - uses: actions/setup-node@v4.0.0
        with:
          node-version: 21

      - name: install cypress
        run: npm ci

      - name: start webserver
        run: python -mhttp.server&

      - name: determine cypress version
        run: echo "CY_VERSION=$(npx cypress --version --component package)" >> $GITHUB_ENV

      - name: run tests against chrome
        run: >
          docker run -v `pwd`:/e2e -w /e2e --network=host
          cypress/included:${CY_VERSION} cypress run --browser chrome

      - name: run tests against firefox
        run: >
          docker run -v `pwd`:/e2e -w /e2e --network=host
          cypress/included:${CY_VERSION} cypress run --browser firefox

      - name: run tests against electron
        run: npx cypress run

...
